<?php
require(__DIR__.DIRECTORY_SEPARATOR."../../common/protect.php");


echo '<link rel="stylesheet" type="text/css" href="module/_footer/style.css" />';

?>

<div id="footer_div">
	<div class="footer_spliter"></div>
	<div class="center">If you have any question, please contact issuemyvisatoday@gmail.com</div>
        <div class="center"><p>Disclaimer: Some of the data in this site comes from checkee.info. They are marked out clearly.
            The notification generated by this site does not represent the official visa case status. USE AT YOUR OWN RISK!</p>
            <p>声明： 本网站部分数据同步自checkee.info。这部分数据有清楚的标记。本网站发送的状态通知不具官方效力。请自担风险！</p>
        </div>
</div>